### PR TITLE
Check iterator for validity before dereferencing

### PR DESCRIPTION
**Pull request by ericfischer**

### CODE REVIEW

**Comment by springmeyer** [comment]
@ericfischer nice fix and find. Do we have test coverage for the crash this is fixing to ensure it cannot re-appear? /cc @flippmoke

**Comment by ericfischer** [comment]
@springmeyer I'm not sure why it wasn't previously caught by the

    env: CXX=clang++ BUILDTYPE=Debug CXXFLAGS="-fsanitize=address" MASON_CLANG=true

case in travis, since that was what exposed it for me when running manually.

Maybe the travis build isn't including all the tests? From the logs it looks like it is running 2900 of them, compared to 3120 when I run it manually. I don't understand how the `geometry-test-data` integration works so maybe travis has an old copy of the tests?

**Comment by springmeyer** [comment]
> I'm not sure why it wasn't previously caught by the

Looks like there is no test coverage for the `itr_rev == path_geometry.rend()` case so that line was never hit on travis. This lacking coverage is visual at https://codecov.io/gh/mapbox/wagyu/src/4ee647837f4f7eba44f5eb0e63ec668f8cc2187e/include/mapbox/geometry/wagyu/build_edges.hpp#L81

> since that was what exposed it for me when running manually.

When running via tippecanoe or running wagyu alone locally?

**Comment by ericfischer** [comment]
@springmeyer Originally in the context of tippecanoe, but then when running wagyu alone (with the `tests/geometry-test-data/input-polyjson/stairstep.json` file that had caused the crash within tippecanoe).

**Comment by ericfischer** [comment]
Looks like the code path [is covered now](https://codecov.io/gh/mapbox/wagyu/src/bf80b21b34a886ecccd94433388166750c758b77/include/mapbox/geometry/wagyu/build_edges.hpp#L83) by updated tests.

**Comment by flippmoke** [comment]
@ericfischer you need to update the git submodule for geometry-test-data in order for it to be updated properly.

**Comment by ericfischer** [comment]
Thanks @flippmoke. @springmeyer just showed me how to do that.

**Comment by springmeyer** [comment]
> Looks like the code path is covered now by updated tests.

🎉  thanks @ericfischer!

**Pull request merged**
