### PR TITLE
std::round is not defined in some platforms

### PR DESCRIPTION
**Pull request by tmpsantos**
Use the C version.

Fixes build on Android + GCC.

### CODE REVIEW

**Comment by flippmoke** [comment]
Is there any difference in the results of the C version? Rounding properly gets really important in the process, if you run the fuzzer for a couple hours you will be able to tell if this changed any results.

**Comment by tmpsantos** [comment]
`cmath` is the same implementation as `math.h`, but is C++-ish, with typesafe definitions and namespace. For `round()` it won't matter.

That is why it works with `::round` without including `math.h`, because internally, `cmath` includes `math.h`.

https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-3.4/cmath.html

```
This is a Standard C++ Library file. You should #include this file in your programs, rather than any of the "*.h" implementation files.
This is the C++ version of the Standard C Library header math.h, and its contents are (mostly) the same as that header, but are all contained in the namespace std.

Definition in file cmath.
```

**Comment by flippmoke** [comment]
@tmpsantos are you going to need a minor version bump and a new version via mason? If so lets go ahead and make the changes in this pull request for it and then merge

**Comment by flippmoke** [comment]
Ran the fuzzer anyhow on this as well, passed 15 million tests or so with out any failures 👍

**Comment by tmpsantos** [comment]
> If so lets go ahead and make the changes in this pull request for it and then merge

Done, waiting for your :green_apple:

**Comment by brunoabinader** [comment]
`std::round` and `::round` are the same: the example in http://cpp.sh/3wp5h prints out the same memory address for both.

**Pull request merged**
