### PR TITLE
Quickclip

### PR DESCRIPTION
**Pull request by flippmoke**
A faster clipping technique for very large polygons and clipping specifically for bounding boxes.

### CODE REVIEW

**Comment by springmeyer** [comment]
> A faster clipping technique for very large polygons and clipping specifically for bounding boxes.

So this is faster because it only supports clipping by bbox? Are there any tradeoffs other than that constraint?

**Comment by flippmoke** [comment]
@springmeyer this is a faster form of clipping for very large polygons where a smaller area is being clipped. This is the technique that [tippaecanoe](https://github.com/mapbox/tippecanoe/) uses to clip and it seems to be much faster. Basically it greatly reduces the size of the data used prior to being sent to wagyu, and has wagyu used as a polygon correction step (by using a union) over a clipping operation.

**Comment by mourner** [comment]
The distinct property of Sutherland-Hodgeman is that clipping a concave polygon or polygon with holes can produce polygons with degenerate zero-area parts. Does the subsequent wagyu correction process get rid of them?

**Comment by ericfischer** [comment]
@mourner In this case the clip is always square so concavity isn't a problem, but wagyu does have to clean up the degenerate parts when there are holes.

**Comment by mourner** [comment]
@ericfischer there are often degenerate parts when clipping a concave polygon by a square. So wagyu currently don't remove such degeneracies?

**Comment by ericfischer** [comment]
@mourner Sorry, I thought you meant a concave clip region, not a concave polygon. To the best of my knowledge, Wagyu cleans up those degeneracies correctly after Sutherland-Hodgman clipping, which is what Tippecanoe already does as a quick first pass to clip to the tile boundary before using Wagyu to clean up what remains.

**Comment by ericfischer** [comment]
@flippmoke I am having a hard time believing that the single-pass approach will be faster than the simple approach. I did a [quick test](https://github.com/mapbox/wagyu/blob/quickclip/tests/quick_clip_profile.cpp) of random polygons, and the straightforward 4-pass Sutherland-Hodgman implementation runs in about 1/5 the time of the still-buggy single-pass implementation.

**Comment by flippmoke** [comment]
@ericfischer then lets go with the more traditional approach!

**Comment by ericfischer** [comment]
OK, I'll trim down the source file so we can get this merged. We can always bring back more complexity later if it turns out to be useful.

**Pull request merged**
