### PR TITLE
geometry.hpp as a mason dependency

### PR DESCRIPTION
**Pull request by mapsam**
Working on #8 

- [x] Add install script to Makefile
- [x] `.mason` submodule
- [x] properly include geometry in the includes path?

Not exactly sure how to get the third one done properly. Some help from @springmeyer would be great!

### CODE REVIEW

**Comment by springmeyer** [comment]
> properly include geometry in the includes path?

You could use `$(.mason/mason prefix geometry 0.7.0)/include` but I prefer:

- Add `-Imason_packages/.link/include` to the CXXFLAGS
- Then run `mason link geometry 0.7.0` in addition to `mason install geometry 0.7.0` which will create `./mason_packages/.link/include`

Then when you delete the bundled geometry.hpp files the build should continue working.

**Comment by mapsam** [comment]
Perfect @springmeyer - thanks! This is up and running successfully. I removed the tracked geometry.hpp files as well.

**Comment by springmeyer** [comment]
@mapsam - great, in terms of travis you need to switch the `.gitmodules` to use `url = https://github.com/mapbox/mason.git` in order for non ssh connections.

**Comment by mapsam** [comment]
Ah, thanks @springmeyer - hadn't even looked at travis yet. Updated!

**Comment by mapsam** [comment]
@springmeyer where do you think it's best to add `make mapnik_packaging` command?

**Comment by springmeyer** [comment]
This is now as green as possible. Master has an address sanitizer crash that @flippmoke is on the hook to fix and a warning that is leading to an error with g++. Both are hitting this branch but unrelated, so merging this. Nice work @mapsam!

**Comment by mapsam** [comment]
\o/

**Pull request merged**
